version: '3'

services:
    workspace:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        environment:
            PYTHONPATH: /workspace
        volumes:
            - ..:/workspace
        env_file:
            - .env
        command: sleep infinity